version: '3.11'

services:
  howlong_mu_won:
    container_name: howlong_mu_won
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - .:/app
    # depends_on:
    #   - db
#   db:
#     container_name: db
#     image: postgres:12
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#       - POSTGRES_DB=postgres
#     ports:
#       - 5432:5432
#     volumes:
#       - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata: {}