# Generated by Django 5.0 on 2023-12-31 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('numTrophies', models.IntegerField()),
                ('numWins', models.IntegerField()),
                ('numLosses', models.IntegerField()),
                ('numTies', models.IntegerField()),
                ('leadFrom', models.DateField()),
                ('leadTo', models.DateField()),
                ('moneySpent', models.IntegerField()),
            ],
        ),
    ]
