# Generated by Django 5.0 on 2024-01-01 04:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0002_remove_coach_age_coach_dob_alter_coach_leadfrom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='statURL',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='leadFrom',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='coach',
            name='leadTo',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
