# Generated by Django 5.0 on 2024-01-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0004_remove_coach_moneyspent'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='moneySpent',
            field=models.IntegerField(default=0),
        ),
    ]
