# Generated by Django 5.0 on 2024-01-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0006_coach_numplayersused_coach_shortdesc'),
        ('trophies', '0005_remove_trophy_lastwonby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='numTrophies',
        ),
        migrations.AddField(
            model_name='coach',
            name='trophyWon',
            field=models.ManyToManyField(related_name='trophyWon', to='trophies.trophy'),
        ),
    ]
