# Generated by Django 5.0 on 2024-01-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0008_alter_coach_trophywon'),
        ('trophies', '0005_remove_trophy_lastwonby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='trophyWon',
            field=models.ManyToManyField(blank=True, related_name='trophyWon', to='trophies.trophy'),
        ),
    ]
