# Generated by Django 5.0 on 2024-02-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0009_alter_coach_trophywon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='moneySpent',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
