# Generated by Django 5.0 on 2024-01-01 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trophies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trophy',
            name='lastWonBy',
        ),
    ]
