# Generated by Django 5.0 on 2024-01-01 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0001_initial'),
        ('trophies', '0002_remove_trophy_lastwonby'),
    ]

    operations = [
        migrations.AddField(
            model_name='trophy',
            name='lastWonBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coaches.coach'),
        ),
    ]
