# Generated by Django 5.0 on 2024-01-15 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trophies', '0004_alter_trophy_lastwonby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trophy',
            name='lastWonBy',
        ),
    ]
