# Generated by Django 5.0 on 2023-12-31 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coaches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('numGamesPlayed', models.IntegerField()),
                ('playFrom', models.DateField()),
                ('playTo', models.DateField()),
                ('statURL', models.CharField(max_length=200)),
                ('boughtBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coaches.coach')),
                ('workWith', models.ManyToManyField(related_name='workWith', to='coaches.coach')),
            ],
        ),
    ]
