# Generated by Django 5.0 on 2024-01-02 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_position_player_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='price',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='playTo',
            field=models.DateField(null=True),
        ),
    ]
