# Generated by Django 5.0 on 2024-01-14 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0004_remove_coach_moneyspent'),
        ('players', '0005_alter_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='boughtBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boughtBy', to='coaches.coach'),
        ),
    ]
