# Generated by Django 5.0 on 2024-02-17 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0009_alter_coach_trophywon'),
        ('players', '0008_alter_player_workwith'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='workWith',
            field=models.ManyToManyField(blank=True, related_name='workWith', to='coaches.coach'),
        ),
    ]
